// Search functions for the fixed-search DP mode.

// Now with less complexity.

// The objective is to find a series of bits (e.g. 0100010010001001) in a
// stream generated by pulse delays (each of which correspond to a number of
// zeroes followed by a trailing one).

// The string search is intended to be part of a dynamic programming solver
// that also determines the most likely base frequency for the clock. The
// string search is used as part of the fixed-sequence mode, where usual
// penalties for violating the MFM spec are disabled. (This because certain
// floppy headers, A1A1A1 and C2C2C2, intentionally violate the spec as a
// way to signal their out-of-band nature.) To prevent false positives that
// only match, say, the first two bits of the needle, the DP machine must
// pay a "start-up penalty" when going into fixed-sequence mode.

// The difficulty lies in that the whole process must be done step-by-step
// through an explicit state (i.e. no loops) due to its incorporation into
// a DP grid.

// The way I'll represent this problem is that both the needle (series of
// bits to find) and the haystack (pulses we're searching through) are
// represented by their number of zero bits. If required, the initial and
// final needle values are marked half-open, so that haystack pulse lengths
// that are equal to or longer than it will match.

// For instance, in the example above, "01" should match haystacks of "01",
// "001", and "0001", because they all contain the suffix 01. This translates
// to the haystack number of zero bits needing to be equal or greater than
// the number of needle bits.

// Consecutive matches are not allowed; a match can't start at the same delay
// that the previous one ended. We'll get around the edge cases by just adding
// more needles instead; I tried to implement consecutive matches but they
// were too much of a hassle.

// ....
// I think there may be a problem here. Suppose the needle is
// A1A1A1FB. Suppose the haystack is A1A1A1A1FB. When the DP hits the second
// A1, it's faced with a choice of whether to build on the already existing
// search (that has already matched A1 once) or to start a new one. Suppose
// we go with the existing match. Then the fourth A1 will fail to match, even
// though there would have been a match if we'd discarded the first A1.
// Similarly, if we would always start anew, then a haystack of 00A1A1A1FB would
// fail.
// Hence, if we fail an ordinary compare(), we would need to check if some suffix
// of what we already matched, is consistent with a continuation at the current
// pulse length. But this again leads to a problem. Suppose that we have again
// a haystack of A1A1A1A1FB with all A1s out-of-band, and we have some MFM penalty.
// Suppose that at the fourth A1, the logic says: okay, a fourth A1 doesn't match
// our needle, but the suffix A1A1 matches a third A1, so we can use that. But then
// the first A1 got off without paying for its MFM violation.
// It's possible this could be circumvented by using very complex penalties, but
// there could be a ripple effect. The only *real* way to do this is to make the
// number of common prefixes into an index, and we're already strapped for space
// as is...
// Ponder this more later.

#pragma once

#include <iostream>
#include <iterator>
#include <vector>
#include <string>

class needle_spec {
	public:
		bool first_half_open, last_half_open;
		std::vector<int> num_zeroes;

		void set(std::string needle_str);
		needle_spec() {}
		needle_spec(std::string needle_str) {
			set(needle_str);
		}

};

// Helper functions for translating strings into the proper format.
// Note: this assumes no consecutive ones (which isn't legal by MFM
// anyway, so not something we have to care about).
std::vector<int> get_num_zeroes(std::string bitstring) {
	std::vector<int> num_zeroes;

	size_t current_num_zeroes = 0;

	for (size_t i = 0; i < bitstring.size(); ++i) {
		if (bitstring[i] == '1') {
			if (current_num_zeroes != 0) {
				num_zeroes.push_back(current_num_zeroes);
				current_num_zeroes = 0;
			}
		} else {
			++current_num_zeroes;
		}
	}

	if (current_num_zeroes != 0) {
		num_zeroes.push_back(current_num_zeroes);
	}

	return num_zeroes;
}

void needle_spec::set(std::string needle_str) {

	// If the needle starts with a one, then the subsequent zeroes
	// are not half-open (because we match the whole follwing pulse
	// delay after the one). Similarly, if the needle ends in a one,
	// the last match is exact too.

	first_half_open = (needle_str[0] != '1');
	last_half_open = (*needle_str.rbegin() != '1');
	num_zeroes = get_num_zeroes(needle_str);
}


class fixed_search_state {
	public:
		bool still_matching = false;
		size_t needle_offset = 0;
		// std::vector<bool> active_needles; <--- once we get multiple needles
};



class fixed_search {
	private:
		needle_spec needle;

	public:
		// Get the first state for a transition from some other mode
		// to starting a search. cur_haystack_num_zeroes is the number of
		// zeroes for the *present* pulse delay - the one that we're
		// transitioning to.
		fixed_search_state get_first_state(
			int cur_haystack_num_zeroes) const;

		fixed_search_state get_next_state(
			const fixed_search_state & last_search_state,
			int cur_haystack_num_zeroes) const;
};

// Do either a fully open or half-open comparison.

bool compare(const needle_spec & needle, size_t needle_idx,
	int cur_haystack_num_zeroes) {

	if (needle_idx >= needle.num_zeroes.size()) {
		return false;
	}

	if (needle.num_zeroes[needle_idx] == cur_haystack_num_zeroes) {
		return true;
	}

	bool half_open = false;

	if (needle_idx == 0 && needle.first_half_open) {
		half_open = true;
	}

	if (needle_idx == needle.num_zeroes.size()-1 &&
		needle.last_half_open) {
		half_open = true;
	}

	if (half_open && needle.num_zeroes[needle_idx] <=
		cur_haystack_num_zeroes) {
		return true;
	}

	return false;
}

fixed_search_state fixed_search::get_first_state(
	int cur_haystack_num_zeroes) const {

	fixed_search_state first;
	first.still_matching = compare(needle, 0, cur_haystack_num_zeroes);
	first.needle_offset = 0;

	return first;
}

fixed_search_state fixed_search::get_next_state(
	const fixed_search_state & last_search_state,
	int cur_haystack_num_zeroes) const {

	fixed_search_state next;
	next.needle_offset = last_search_state.needle_offset+1;
	next.still_matching = last_search_state.still_matching &&
		compare(needle, next.needle_offset, cur_haystack_num_zeroes);

	return next;
}