// Search functions for the fixed-search DP mode.

// The objective is to find a series of bits (e.g. 0100010010001001) in a
// stream generated by pulse delays (each of which correspond to a number of
// zeroes followed by a trailing one).

// The string search is intended to be part of a dynamic programming solver
// that also determines the most likely base frequency for the clock. The
// string search is used as part of the fixed-sequence mode, where usual
// penalties for violating the MFM spec are disabled. (This because certain
// floppy headers, A1A1A1 and C2C2C2, intentionally violate the spec as a
// way to signal their out-of-band nature.) To prevent false positives that
// only match, say, the first two bits of the needle, the DP machine must
// pay a "start-up penalty" when going into fixed-sequence mode.

// The difficulty lies in the edge cases and that the whole process must
// be done step-by-step through an explicit state (i.e. no loops) due to
// its incorporation into a DP grid.

// The way I'll represent this problem is that both the needle (series of
// bits to find) and the haystack (pulses we're searching through) are
// represented by their number of zero bits. If required, the initial and
// final needle values are marked half-open, so that haystack pulse lengths
// that are equal to or longer than it will match.

// For instance, in the example above, "01" should match haystacks of "01",
// "001", and "0001", because they all contain the suffix 01. This translates
// to the haystack number of zero bits needing to be equal or greater than
// the number of needle bits.

// We also need to handle consecutive matches. These are allowed, but we
// still need to add a start-up penalty for each instance.
// E.g. suppose that the needle is 01000. A haystack of 000100010001 should
// only match once, either 00[01000]10001 or 000100[01000]1, but not be allowed
// to extend the first match into another match, despite all three runs having
// at least one zero bit.

// All of this should be tested, because I don't trust myself with this
// many edge cases.

// And it'll be kinda ugly because I don't have a proper test library
// yet. TODO, fix that later.

#pragma GCC diagnostic ignored "-Wunused-but-set-variable"

#include <iostream>
#include <iterator>
#include <vector>
#include <string>

class needle_spec {
	public:
		bool first_half_open, last_half_open;
		std::vector<int> num_zeroes;
};

// Helper functions for translating strings into the proper format.
// Note: this assumes no consecutive ones (which isn't legal by MFM
// anyway, so not something we have to care about).
std::vector<int> get_num_zeroes(std::string bitstring) {
	std::vector<int> num_zeroes;

	size_t current_num_zeroes = 0;

	for (size_t i = 0; i < bitstring.size(); ++i) {
		if (bitstring[i] == '1') {
			if (current_num_zeroes != 0) {
				num_zeroes.push_back(current_num_zeroes);
				current_num_zeroes = 0;
			}
		} else {
			++current_num_zeroes;
		}
	}

	if (current_num_zeroes != 0) {
		num_zeroes.push_back(current_num_zeroes);
	}

	return num_zeroes;
}

needle_spec get_needle(std::string needle_str) {
	needle_spec out;

	// If the needle starts with a one, then the subsequent zeroes
	// are not half-open (because we match the whole follwing pulse
	// delay after the one). Similarly, if the needle ends in a one,
	// the last match is exact too.

	out.first_half_open = (needle_str[0] != '1');
	out.last_half_open = (*needle_str.rbegin() != '1');
	out.num_zeroes = get_num_zeroes(needle_str);

	return out;
}

// Do either a fully open or half-open comparison.

// previous_ok: If we're checking a haystack index that was part
// of a previous successful match, against the first needle index,
// and that needle index is half-open, then we require an exact
// match. This prevents false positives with consecutive matches:
// one way to look at this is that the extra bits of the haystack
// have been used up by the previous match and so can't be used
// again.
// This will need more sophisticated logic later.
// Needs to be "number of zeroes spoken for".
bool compare(const needle_spec & needle, size_t needle_idx,
	int cur_haystack_num_nonzeroes, bool previous_ok) {

	if (needle.num_zeroes[needle_idx] == cur_haystack_num_nonzeroes) {
		return true;
	}

	bool half_open = false;

	if (needle_idx == 0 && needle.first_half_open && !previous_ok) {
		half_open = true;
	}

	if (needle_idx == needle.num_zeroes.size()-1 &&
		needle.last_half_open) {
		half_open = true;
	}

	if (half_open && needle.num_zeroes[needle_idx] <=
		cur_haystack_num_nonzeroes) {
		return true;
	}

	return false;
}


// Returns a vector with 0 where a match to the beginning of the
// needle was found, 1 for interior, and 2 for the end. The
// output values are relative to the given start haystack index.
// This is purely for testing - in the real DP system, these values
// would be used to guide the transition from other modes to the
// fixed-sequence mode as well as its penalties.
std::vector<int> get_match_status(const std::vector<int> &
	num_zeroes_haystack, const needle_spec & needle,
	size_t haystack_start_pos) {

	size_t haystack_len = num_zeroes_haystack.size(),
		needle_len = needle.num_zeroes.size();

	std::vector<int> status;

	size_t i = haystack_start_pos;

	bool ok = true;
	bool previous_ok = false;
	size_t last_state, last_num_zeroes_matched;

	while (i < haystack_len) {
		for (size_t j = 0; j < needle_len && j+i < haystack_len && ok; ++j) {
			ok &= compare(needle, j, num_zeroes_haystack[j+i],
				previous_ok);
			if (!ok) {
				return status;
			}

			last_num_zeroes_matched = needle.num_zeroes[j];

			if (j == 0) {
				status.push_back(0);
				last_state = 0;
				continue;
			}

			if (j == needle_len-1) {
				status.push_back(2);
				last_state = 2;
				continue;
			}

			status.push_back(1);
			last_state = 1;
		}

		// TODO: If we have a state 2, then it may be possible to start another
		// match pattern right away. This should be checked with j = 1; because
		// we don't want to pay the penalty *again* if there's no second pattern
		// (or we just don't want to match twice).

		// Ugh, this is getting hard to reason about.
		// Maybe I should just say YAGNI.
		// Yeah, I think so...

		i += needle_len;
	}

	return status;
}

class match {
	public:
	size_t start, end;
	match(size_t s, size_t e) : start(s), end(e) {}
};

std::vector<match> get_matching_indices(
	std::string haystack_str, std::string needle_str,
	bool only_full_matches) {

	needle_spec needle = get_needle(needle_str);
	std::vector<int> num_zeroes_haystack = get_num_zeroes(haystack_str);

	// Plain old O(n^2) search algorithm.

	size_t haystack_len = num_zeroes_haystack.size(),
		needle_len = needle.num_zeroes.size();

	std::vector<match> match_indices;

	// Handle invalid inputs
	if ((haystack_len < needle_len) || needle_len == 0) {
		return match_indices;
	}

	for (size_t i = 0; i < haystack_len - needle_len + 1; ++i) {
		// Quick and dirty
		std::vector<int> possible_match = get_match_status(
			num_zeroes_haystack, needle, i);
		if (possible_match.empty()) {
			continue;
		}

		if (only_full_matches && possible_match.size() < needle_len) {
			continue;
		}

		match_indices.push_back(match(i, i+possible_match.size()));
	}

	return match_indices;
}

size_t get_num_overlapping_matches(std::string haystack_str,
	std::string needle_str) {

	return get_matching_indices(
		haystack_str, needle_str, true).size();
}

size_t get_num_nonoverlapping_matches(std::string haystack_str,
	std::string needle_str) {

	std::vector<match> match_indices = get_matching_indices(
		haystack_str, needle_str, true);

	// Only count those matches that don't overlap with some
	// earlier match. This will count something like
	// haystack: 000100010001, needle 01000 only once, whereas
	// there are two overlapping matches,
	// 00[01000]10001 and 000100[01000]1.

	size_t first_allowed_start = 0;
	size_t num_nonoverlapping_matches = 0;

	for (const match & m: match_indices) {
		if (first_allowed_start >= m.start) {
			++num_nonoverlapping_matches;
			first_allowed_start = m.end + 1;
		}
	}

	return num_nonoverlapping_matches;
}

bool contains(std::string haystack_str,
	std::string needle_str) {

	return get_matching_indices(
		haystack_str, needle_str, true).size() > 0;
}

int main() {
	// Test cases
	std::string haystack = "0001000100100010010010100100101",
		needle = "0100010010001001";

	if (!contains(haystack, needle)) {
		std::cout << "Test failure (match)\n";
	}

	std::string haystack_at_beginning = "00101",
		needle_at_beginning = "001";

	if (!contains(haystack_at_beginning, needle_at_beginning)) {
		std::cout << "Test failure (match at the end)\n";
	}

	std::string haystack_at_end = "01001",
		needle_at_end = "001";

	if (!contains(haystack_at_end, needle_at_end)) {
		std::cout << "Test failure (match at the end)\n";
	}

	std::string haystack_ii = "000100010010001010010100100101";

	if (contains(haystack_ii, needle)) {
		std::cout << "Test failure (no match)\n";
	}

	// This should match twice
	std::string haystack_twice = "00101001",
		needle_twice = "001";

	if (get_num_overlapping_matches(haystack_twice, needle_twice) != 2) {
		std::cout << "Test failure (match twice)\n";
	}

	// Overlapping case: this should only match once.
	//    00[0100 0]10001
	// or 00 0100[01000]1
	std::string haystack_overlap = "000100010001",
		needle_overlap = "01000";

	if (get_num_overlapping_matches(haystack_overlap, needle_overlap) != 2) {
		std::cout << "Test failure (overlap test, overlapping matches)\n";
	}

	if (get_num_nonoverlapping_matches(haystack_overlap, needle_overlap) != 1) {
		std::cout << "Test failure (overlap test, nonoverlapping matches)\n";
	}

	// More distant overlapping
	haystack_overlap = "001001001001";
	needle_overlap = "001001001";

	if (get_num_overlapping_matches(haystack_overlap, needle_overlap) != 2) {
		std::cout << "Test failure (distant overlap test, overlapping matches)\n";
	}

	if (get_num_nonoverlapping_matches(haystack_overlap, needle_overlap) != 1) {
		std::cout << "Test failure (distant overlap test, nonoverlapping matches)\n";
	}

	// But this should match twice because there's room for it.
	// That is, we can match 0[010][010] without overlapping any
	// bits, even though we overlap pulse delay indices.
	std::string haystack_permitted_overlap = "000100010",
		needle_permitted_overlap = "010";

	if (get_num_nonoverlapping_matches(haystack_permitted_overlap,
		needle_permitted_overlap) != 2) {
		std::cout << "Test failure (permitted overlapping)\n";
	}
}