// Search functions for the fixed-search DP mode.

// The objective is to find a series of bits (e.g. 0100010010001001) in a
// stream generated by pulse delays (each of which correspond to a number of
// zeroes followed by a trailing one).

// The difficulty lies in the edge cases and that the whole process must
// be done step-by-step through an explicit state (i.e. no loops).

// The way I'll represent this problem is that both the needle (series of
// bits to find) and the haystack (pulses we're searching through) are
// represented by their number of zero bits. If required, the initial and
// final needle values are marked half-open, so that haystack pulse lengths
// that are equal to or longer than it will match.

// For instance, in the example above, "01" should match haystacks of "01",
// "001", and "0001", because they all contain the suffix 01. This translates
// to the haystack number of zero bits needing to be equal or greater than
// the number of needle bits.

// We also need to handle consecutive matches: suppose that the needle is
// 01000. A haystack of 000100010001 should only match once, either
// 00[01000]10001 or 000100[01000]1, despite all three runs having at least
// one zero bit.

// All of this should be tested, because I don't trust myself with this
// many edge cases.

// And it'll be kinda ugly because I don't have a proper test library
// yet. TODO, fix that later.

#include <iostream>
#include <iterator>
#include <vector>
#include <string>

class needle_spec {
	public:
		bool first_half_open, last_half_open;
		std::vector<int> num_zeroes;
};

// Helper functions for translating strings into the proper format.
// Note: this assumes no consecutive ones (which isn't legal by MFM
// anyway, so not something we have to care about).
std::vector<int> get_num_zeroes(std::string bitstring) {
	std::vector<int> num_zeroes;

	size_t current_num_zeroes = 0;

	for (size_t i = 0; i < bitstring.size(); ++i) {
		if (bitstring[i] == '1') {
			if (current_num_zeroes != 0) {
				num_zeroes.push_back(current_num_zeroes);
				current_num_zeroes = 0;
			}
		} else {
			++current_num_zeroes;
		}
	}

	if (current_num_zeroes != 0) {
		num_zeroes.push_back(current_num_zeroes);
	}

	return num_zeroes;
}

needle_spec get_needle(std::string needle_str) {
	needle_spec out;

	// If the needle starts with a one, then the subsequent zeroes
	// are not half-open (because we match the whole follwing pulse
	// delay after the one). Similarly, if the needle ends in a one,
	// the last match is exact too.

	out.first_half_open = (needle_str[0] != '1');
	out.last_half_open = (*needle_str.rbegin() != '1');
	out.num_zeroes = get_num_zeroes(needle_str);

	return out;
}

// Do either a fully open or half-open comparison.
bool compare(const needle_spec & needle, size_t needle_idx,
	int cur_haystack_num_nonzeroes) {

	if (needle.num_zeroes[needle_idx] == cur_haystack_num_nonzeroes) {
		return true;
	}

	bool half_open = false;

	if (needle_idx == 0 && needle.first_half_open) {
		half_open = true;
	}

	if (needle_idx == needle.num_zeroes.size()-1 &&
		needle.last_half_open) {
		half_open = true;
	}

	if (half_open && needle.num_zeroes[needle_idx] <=
		cur_haystack_num_nonzeroes) {
		return true;
	}

	return false;
}

std::vector<int> get_matching_indices(
	std::string haystack_str, std::string needle_str) {

	needle_spec needle = get_needle(needle_str);
	std::vector<int> num_zeroes_haystack = get_num_zeroes(haystack_str);

	// Plain old O(n^2) search algorithm.
	// Do explicit state later.

	size_t haystack_len = num_zeroes_haystack.size(),
		needle_len = needle.num_zeroes.size();

	std::vector<int> matches;

	// Handle invalid inputs
	if ((haystack_len < needle_len) || needle_len == 0) {
		return matches;
	}

	for (size_t i = 0; i < haystack_len - needle_len + 1; ++i) {
		bool ok = true;
		for (size_t j = 0; j < needle_len && ok; ++j) {
			ok &= compare(needle, j, num_zeroes_haystack[j+i]);
		}
		if (ok) {
			matches.push_back(i);
		}
	}

	std::cout << "\n";

	return matches;
}

size_t get_num_matches(std::string haystack_str,
	std::string needle_str) {

	return get_matching_indices(
		haystack_str, needle_str).size();
}

bool contains(std::string haystack_str,
	std::string needle_str) {

	return get_matching_indices(
		haystack_str, needle_str).size() > 0;
}

int main() {
	// Test cases
	std::string haystack = "0001000100100010010010100100101",
		needle = "0100010010001001";

	if (!contains(haystack, needle)) {
		std::cout << "Test failure (match)\n";
	}

	std::string haystack_at_beginning = "00101",
		needle_at_beginning = "001";

	if (!contains(haystack_at_beginning, needle_at_beginning)) {
		std::cout << "Test failure (match at the end)\n";
	}

	std::string haystack_at_end = "01001",
		needle_at_end = "001";

	if (!contains(haystack_at_end, needle_at_end)) {
		std::cout << "Test failure (match at the end)\n";
	}

	std::string haystack_ii = "000100010010001010010100100101";

	if (contains(haystack_ii, needle)) {
		std::cout << "Test failure (no match)\n";
	}

	// This should match twice
	std::string haystack_twice = "00101001",
		needle_twice = "001";

	if (get_num_matches(haystack_twice, needle_twice) != 2) {
		std::cout << "Test failure (match twice)\n";
	}

	// Overlapping case: this should only match once.
	std::string haystack_overlap = "000100010001",
		needle_overlap = "01000";

	if (get_num_matches(haystack_overlap, needle_overlap) != 1) {
		std::cout << "Test failure (overlapping)\n";
	}
}